### PR TITLE
Adding Taring the backup, and Adding Backup to game.ini

### PR DESCRIPTION
**Pull request by Budman17r**
Game.ini has additional settings, I did not see this getting backed up before

### CODE REVIEW

**Comment by Budman17r** [comment]
Sorry me and Github have been fighting, I'm a pain I know

**Comment by Budman17r** [comment]
image

This is how it looks.  Game.ini was missing in the original backup.

**Comment by FezVrasta** [comment]
Maybe we may also let the user know about the name of the archive created?

I mean, we copy everything, compress, and then we say "Backup completed as <archive_name>.tar.bz"

**Comment by Budman17r** [comment]
Good Idea I like it. 
image

**Comment by Budman17r** [comment]
Compress directory is now compressing backup.

**Comment by FezVrasta** [comment]
It looks good to me, waiting peer review by @klightspeed and/or @Atriusftw

**Comment by klightspeed** [comment]
It looks good to me.

**Comment by Budman17r** [comment]
woohoo my first commit ever :)

**Comment by FezVrasta** [comment]
:smiley:

**Pull request merged**
