### PR TITLE
Added option to validate + typo fix

### PR DESCRIPTION
**Pull request by AniMud**

### CODE REVIEW

**Comment by FezVrasta** [comment]
is this really required? maybe we should just an option to the current install argument

**Comment by AniMud** [comment]
I added it to my installation because i thought there was an issue with an update. Turns out the devs just pushed a broken linux server update, which prevented the server from starting. I figured it would be fine to have as a separate option

Date: Thu, 2 Jul 2015 13:45:10 -0700

**Comment by Sispheor** [comment]
@FezVrasta +1
Just add to the current install function should be ok.

**Comment by FezVrasta** [comment]
@AniMud check out how the `update --force` argument works and please do the same with your feature. Thanks!

**Pull request closed without merging**
