### PR TITLE
release 1.2

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by FezVrasta** [comment]
does it look okay?

**Comment by klightspeed** [comment]
Probably the only issues I can see are:
* https://github.com/FezVrasta/ark-server-tools/blob/1.2-dev/tools/arkmanager#L83
  A typo - says the SteamCMD exec could not be found, when it should say the ARK server exec could not be found.
* https://github.com/FezVrasta/ark-server-tools/blob/1.2-dev/tools/openrc/arkdaemon#L12
  A typo - should be `need net`, not `require net`

**Comment by FezVrasta** [comment]
anything else?

**Comment by Atriusftw** [comment]
Do any of you have the opportunity to test this version before pushing it to master?

**Comment by Climax87** [comment]
Is there any Rcon tool out there for Ark Servers - something like HLSW ?

**Comment by klightspeed** [comment]
@Climax87 1.3-dev has a very minimal RCON client.

However, any Source RCON Protocol client should work - e.g. mcrcon, ARKon, or [ASY]Zyrain's rcon.c

**Comment by Climax87** [comment]
thanks man :)

**Pull request merged**
