### PR TITLE
Force mod branch to be Windows

### PR DESCRIPTION
**Pull request by klightspeed**
The Linux versions of mods don't work, and probably never will, in the ARK server.

### CODE REVIEW

**Comment by FezVrasta** [comment]
May I know why? I don't get it.

**Comment by klightspeed** [comment]
@arkfrancegaming had `mod_branch=Linux` in October last year in #252, and despite asking him to change it to `mod_branch=Windows`, he still had `mod_branch=Linux` in #385.

**Comment by FezVrasta** [comment]
I don't get why should we prevent someone from use the linux branch if he wants to...

Maybe add a warn saying that is most likely that he wants to use the windows branch?

**Comment by klightspeed** [comment]
I'll close this and create a new one warning of known compatibility issues when `mod_branch=Linux`

**Comment by FezVrasta** [comment]
thanks!

**Pull request closed without merging**
