### PR TITLE
Allow backing up prior to updating the server

### PR DESCRIPTION
**Pull request by Atriusftw**
Two simple commits to make life easier with these frequent updates to ARK.

* Controllable by true/false in the configuration files.
* Only performs a backup if there actually is a new version available.

### CODE REVIEW

**Comment by Atriusftw** [comment]
Mentions for review;

@FezVrasta 
@klightspeed 

:squirrel:

**Comment by klightspeed** [comment]
Do you want to backup if a mod update is required?

**Comment by Atriusftw** [comment]
Didn't think about that, but it kinda depends on the mod i guess. Might be useful as they potentially could break things.
Got this idea in the middle of the night :p

**Comment by FezVrasta** [comment]
good idea

**Comment by klightspeed** [comment]
Looks good.

**Pull request merged**
