### PR TITLE
Backport some fixes from the 1.6 development

### PR DESCRIPTION
**Pull request by klightspeed**

### CODE REVIEW

**Comment by klightspeed** [comment]
Shall I merge this?

**Comment by klightspeed** [comment]
@Atriusftw @Sispheor @FezVrasta @arkfrance are you happy for me to merge these as a hotfix to 1.5?

**Comment by FezVrasta** [comment]
yes it's okay to me

**Comment by arkfrance** [comment]
Happy merging ! :dancers:

**Comment by arkfrance** [comment]
Can someone be moderator or something to sort not closed issues ?

**Pull request merged**
