### PR TITLE
Waiting for world save before update.

### PR DESCRIPTION
**Pull request by Rodzynus**
I wrote a function that waits for world save to be done before performing update. I know it's just temporary solution until RCON and save-on-exit is implemented but might be useful until then.
My bash coding is not great so there might be better way to implement that if you come up with something.

### CODE REVIEW

**Comment by FezVrasta** [comment]
wasn't the autosave set to 15 minutes?

**Comment by Rodzynus** [comment]
It is, still wouldn't want almost 15 minute rollback in worst case scenario so I wrote it to minimise that rollback. I can add that command as cron task and it will keep checking for that autosave before killing server.

**Comment by FezVrasta** [comment]
Ahh ok I get how it works now, sorry :) nice idea

**Comment by FezVrasta** [comment]
Sorry I merged it into master, but it's not good.

May you send the PR to the 1.2-dev branch please?

**Pull request merged**
