### PR TITLE
Uninstall text enhancement

### PR DESCRIPTION
**Pull request by axi92**
I hope i made no mistake^^ my first pull request

### CODE REVIEW

**Comment by klightspeed** [comment]
Perhaps `[Y/N]` for both this and the two update messages?

```
  42     read -p "A new version was found! Do you want to upgrade ARK Server Tools to v${arkstLatestVersion}? [Y/N]" -n 1 -r
  49     read -p "A hotfix is available for v${arkstLatestVersion}.  Do you wish to install it? [Y/N]" -n 1 -r
  66   read -p "Are you sure you want to uninstall the ARK Server Tools? [Y/N]" -n 1 -r

```

**Comment by axi92** [comment]
Yes would be nice, I just stumbled over the one message

**Comment by FezVrasta** [comment]
We should provide a default action performed by the `return` button.

    Are you sure? [y/N]

where the capitalized letter is the default action.
This is how it usually works on *unix

**Comment by klightspeed** [comment]
Obsoleted by #369

**Pull request closed without merging**
