### PR TITLE
Dev#1.1

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by FezVrasta** [comment]
If this PR is good please let me know so we can ship

**Comment by klightspeed** [comment]
Looks good to me.

**Comment by Atriusftw** [comment]
Looking through the dffs  right now. Will respond shortly =)

**Comment by FezVrasta** [comment]
:D yeee :smiley:

**Comment by Atriusftw** [comment]
You tagged it as v1.2 though :p

**Comment by Sispheor** [comment]
Yes v1.2. Where is the 1.1? ;)
You can rollback this?

**Comment by Atriusftw** [comment]
It has to either be rolled back or hotfixed.

```
/usr/local/bin/arkmanager: line 130: parseSteamAppVer: command not found
```

It's not defined, i guess parseSteamAppVer -> parseSteamACF?

**Comment by Sispheor** [comment]
Can you test the whole app before tag? We should be sure to deliver a clean
version.

**Pull request merged**
