### PR TITLE
Various fixes for new features

### LINKED ISSUE #488: Command replication
steam@ns3013274:/root$ arkmanager stop --warn
No instances supplied for command stop --warn
Do you wish to run this command for all instances?y
Running command 'stop' for instance 'centpve'
**Le serveur va s'eteindre dans 5 minutes pour une mise a jour de la machine, il y en a pour 20 min en tout
Server received, But no response!!**

Le serveur va s'eteindre dans 5 minutes pour une mise a jour de la machine, il y en a pour 20 min en tout
Server received, But no response!!

There are 17 players connected

The bold one is not too much ?

### LINKED ISSUE #489: Warn command false
i've got the wrong message when i do 

steam@arkfrancegaming:/root$ arkmanager useconfig pve restart --warn
Running command 'restart' for instance 'pve'
Le serveur va redemarrer dans 5 minutes pour une mise a jour de la machine, il y en a pour 25 min en tout

msgWarnReason="Le serveur va redemarrer dans {time} pour {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="pour mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="pour faire la mise a jour de ARK dans (Reboot for ARK update) %d minutes. Les modifications sont disponibles sur notre site http://arkfrancegaming.com/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR"
msgReasonUpdateAppMod="pour mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart="modifier des parametres"
msgReasonShutdown="une mise a jour de la machine, il y en a pour 25 min en tout"

Got the shutdown instead of the restart

### LINKED ISSUE #492: Mods update
Hi,

i think there is a mod update probleme since the merge 

got cronjob using --update-mods every 25 min

but since the update i've got no more logs into workshop_log.txt

i don't think it checks mods update anymore

a mod juste update and nothing happened for at list 1 hour now

i've run an 

steam@arkfrancegaming:/root$ arkmanager useconfig pve update --update-mods --warn
Running command 'update' for instance 'pve'
Downloading mod 519536568/usr/local/bin/arkmanager: ligne 415: /dev/fd/5: Aucun fichier ou dossier de ce type
Mod 519536568 was not successfully downloaded

steam@arkfrancegaming:/root$ arkmanager useconfig pve installmod 680798000
Running command 'installmod' for instance 'pve'
Downloading mod 680798000/usr/local/bin/arkmanager: ligne 415: /dev/fd/5: Aucun fichier ou dossier de ce type
Mod 680798000 was not successfully downloaded
steam@arkfrancegaming:/root$

### PR DESCRIPTION
**Pull request by klightspeed**
__Allow `{time}` in warning reason__
This allows for messages where the time remaining is part of the reason text.

__Fix a typo in the documentation__
The documentation had `{modnamesupdate}` where it should have had `{modnamesupdated}`

__`" \n "` added to empty response message__
Server response when a command returns no response is
`"Server received, But no response!! \n "` where `\n` is a newline.

__Fix an error in doWarn that was causing duplicate warnings__
This should fix #488 

__Actually cancel warning when Ctrl-C etc are pressed__
This should cancel the update / shutdown / restart when the administrator attempts to cancel the update

__Fix warning in `runSteamCMDspinner`__
Fixes a spurious `bad file descriptor` warning

__Fix `restart --warn` broadcasting shutdown message__
This should fix #489 

__Fix error in `runSteamCMDspinnerSubst`__
Fixes a spurious `No such file or directory` error.  Should fix #492

__Fix permission denied error when updating mods__
Fixes a permission denied error when the user running arkmanager does not own stdout.

__Fix spinner__
The previous commit caused the spinner to believe the output not to be a tty.  Fix this.

__Fix Blob SHA breakage__
The Blob SHA wasn't being computed correctly, and netinstall.sh was modifying `arkstVersion` in a way that made the Blob SHA unobtainable.

__`remove-mods` removes mods from workshop directory__
Added new `remove-mods` command, which allows one to remove unwanted mods from the steamcmd workshop directory

__Add `remove-mods` to readme__

__Avoid "no command" message if `remove-mods` is only command__

__Fix mod download not being retried__
Fixes e9b2c9b

__Add `--no-download` option to `update`__
Suggested in #500

__Clean up after SteamCMD if it returns successful__
Sometimes SteamCMD will leave files in the `steamapps/download` directory after successfully updating.  Clean up these files.

__Make arkmanager script sourceable__
This allows the arkmanager script to be `source`able by other scripts.

### CODE REVIEW

**Comment by klightspeed** [comment]
@Sispheor @Atriusftw @FezVrasta @arkfrancegaming Shall I merge this into 1.6-dev?

**Comment by FezVrasta** [comment]
I think it's okay

**Comment by arkfrancegaming** [comment]
Ok for me, just check sometimes the server crash and doesn't auto restart (1.6 unstable)

**Comment by arkfrancegaming** [comment]
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 : 12102 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
21:34:15: Bad PID ''; expected '12102'
21:34:15: exited with status 0
21:34:15: restarting server
21:34:15: Running /home/CENTPVP/ShooterGame/Binaries/Linux/ShooterGameServer Thecenter\?RCONEnabled=True\?RCONPort=27029\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ \[ANTI\ RAID\ OFF\]\?Port=7780\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=****\?MaxPlayers=75\?GameModIds=684959100\,558079412\,656525905\?ForceAllStructureLocking=true\?listen -log -UseBattlEye -servergamelog
21:34:15: Server PID: 13425
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
21:34:20: server is up

**Comment by klightspeed** [comment]
@arkfrancegaming The script is set up so that the server will not automatically restart if the server crashed before it was ready for players to connect.

**Pull request merged**
