### PR TITLE
Tar the Backup files,

### PR DESCRIPTION
**Pull request by Budman17r**
#Tar the files and remove the original Backup Directory.  Saves about 50MB of disk space per backup

### CODE REVIEW

**Comment by FezVrasta** [comment]
I think it's a nice addition, waiting the expert (aka @klightspeed ) for some more feedback :)

**Comment by Budman17r** [comment]
I agree with you, a better way to restore could be nice. 
my scripting skills are still very new lol.

**Comment by Budman17r** [comment]
Modified it to the second one.

**Comment by klightspeed** [comment]
Do we want to use gzip, bzip2, or xz?  The test that @cronner did in #263 suggests that bzip2 results in the best compression ratio, and my test confirms that.

If we want to use bzip2, then replace `-zcvf` with `-jcvf`, and replace `.gz` with `.bz2`.

**Comment by Budman17r** [comment]
Ok updated it again. I appreciate all the feedback you are giving and assistance.

**Comment by klightspeed** [comment]
Looks good.

@FezVrasta do we want to have it print e.g. ` Compressing backup ` followed by the `OK` or `FAILED` status?

**Comment by FezVrasta** [comment]
As you prefer

**Comment by Budman17r** [comment]
image

**Comment by cronner** [comment]
nice, this is going to save alot of harddrive and bandwidth for me, can do alot more backup :D

**Comment by FezVrasta** [comment]
lol there's some problem with the screenshot, wrong spacing between `[` and `OK` and bad alignment. We should use `tabs` instead of `whitespace` to make them aligned

**Comment by Budman17r** [comment]
added the space

**Comment by Budman17r** [comment]
image

image

**Comment by klightspeed** [comment]
This looks good.

**Comment by FezVrasta** [comment]
It should be `[ OK ]` not `[    OK    ]` no?

I'd do:  `/t/t[ OK ]`

**Comment by Budman17r** [comment]
Granted I can modify all of the ok's , so we want 1 space instead of 3?  Just let me know.

**Comment by klightspeed** [comment]
The idea with:
```
[   OK   ]
[ FAILED ]
```
is that those are the same width.

If we prefixed those with e.g. `\e[68G`, then they would all line in the same column.

**Comment by FezVrasta** [comment]
Ah ok I see...

**Comment by Budman17r** [comment]
image

So we want it like that?

**Comment by Budman17r** [comment]
Added that to the file, and modifed all of the OK/Fails

**Comment by FezVrasta** [comment]
Aw it looks great now!

**Comment by Budman17r** [comment]
can we merge it?

**Comment by FezVrasta** [comment]
@Budman17r sorry I've just noticed the target is master, may you move the PR (make a new one) to 1.5-dev? Thanks

**Comment by Budman17r** [comment]
New to github, trying to figure out how to do that

**Pull request closed without merging**
